# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Open Education Analytics
email: your-email@example.com
description: Open Education Analytics is an open community developing modern data intelligence capabilities for global education.
logo: /assets/imgs/img_oea_logo.png

baseurl: "/OpenEduAnalytics" # the subpath of your site, e.g. /blog
<<<<<<< HEAD
<<<<<<< HEAD
url: "https://ivybarley.github.io" # the base hostname & protocol for your site, e.g. http://example.com
=======
url: "https://microsoft.github.io" # the base hostname & protocol for your site, e.g. http://example.com
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> parent of cf92c47 (GH Pages)
=======
url: "https://microsoft.github.io" # the base hostname & protocol for your site, e.g. http://example.com
<<<<<<< HEAD
>>>>>>> parent of cf92c47 (GH Pages)
=======
>>>>>>> parent of cf92c47 (GH Pages)
=======
>>>>>>> parent of cf92c47 (GH Pages)
=======
>>>>>>> parent of cf92c47 (GH Pages)
=======
>>>>>>> parent of cf92c47 (GH Pages)
=======
>>>>>>> parent of cf92c47 (GH Pages)
=======
>>>>>>> parent of cf92c47 (GH Pages)
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  sass_dir: _sass
  style: compressed

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

collections:
  whats_oea:
  modern_data_estate:
  stakeholders:
  challenges:
  use_case_process:
    order:
      - get_started.md
      - define_the_process.md
      - set_up_modern_data_estate.md
      - communicate_and_act.md
      - explore_and_model_data.md
  what_can_you_contribute:
  best_practices_for_contributing:
  new_skills_training:
    order:
      - get_started.md
      - define_the_process.md
      - set_up_modern_data_estate.md
      - communicate_and_act.md
      - explore_and_model_data.md
#    sort_by: step


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
